### ISSUE TITLE
Model toString()

### ISSUE THREAD

**Issue by Scuilion** [Bandwidth/java-sdk#25]
Any objection to adding `toString()` methods to the models classes for user convenience?

**Comment by ajrice6713** [comment]
Hey Kevin,

We do offer a toString method on certain models

https://github.com/Bandwidth/java-sdk/blob/main/src/main/java/com/bandwidth/messaging/models/Media.java#L257
https://github.com/Bandwidth/java-sdk/blob/main/src/main/java/com/bandwidth/messaging/models/BandwidthMessage.java#L325

Is there a certain model in particular you are looking for this functionality on?

**Comment by Scuilion** [comment]
Hey AJ,
I didn't notice those instances or I would have just made a PR :D 
BandwidthCallbackMessage was the one I noticed.

**Comment by ajrice6713** [comment]
Hey Kevin,

This should be what you are looking for:

https://github.com/Bandwidth/java-sdk/blob/94da26f2a8bbeb059b841bebe2acf30d11fc1680/src/main/java/com/bandwidth/messaging/models/BandwidthCallbackMessage.java#L166

**Comment by Scuilion** [comment]
Ah, I guess I should be using version 2.0.0 and not version 1!

Thanks for the help.
