### ISSUE TITLE
Bandwidth Message Api getMediaAsync

### ISSUE THREAD

**Issue by nicolaguido1986** [Bandwidth/java-sdk#56]
I have integrated the bandwidth SDK and I was trying to get a media asynchronously. The text media worked fine, while images are corrupted. 

After debugging I have noticed that the getMediaAsyc does not expect a binary response, hence when I used this method I get a HttpStringResponse.
```

   public CompletableFuture<ApiResponse<InputStream>> getMediaAsync(
            final String accountId,
            final String mediaId) {
        return makeHttpCallAsync(() -> buildGetMediaRequest(accountId, mediaId),
            req -> authManagers.get("messaging").applyAsync(req)
                .thenCompose(request -> getClientInstance()
                        .executeAsync(request, false)),
            context -> handleGetMediaResponse(context));
    }

```

There is any specific reason for this field being false?

**Comment by ajrice6713** [comment]
Hey @nicolaguido1986,

This will go out in the 7.1.1 release on Tuesday March 1st. Thanks for raising this issue up!
